services:
  sublime:
    build: .
    # image: ghcr.io/aaronkyriesenbach/sublime:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - ./data:/data
      - ./movies:/media/movies
      - ./tv:/media/tv
    env_file: .env
    restart: unless-stopped
